author: "Adam Rich, FCAS"
center: "true"
controls: "false"
controlsTutorial: "false"
progress: "false"
slideNumber: "true"
revealjs-url: "../../reveal.js"
theme: "black"
transition: "none"
backgroundTransition: "none"
lang: "en-US"
css: "../../reveal.js/custom.css"
mathjax-url: "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
